version: '3'
services:
  mysql:
    image: "mysql:5.7"
    container_name: "mysql_mygopractice"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Mygopractice123!"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - "/data/mysql_data:/var/lib/mysql"
  mongo:
    image: "mongo:4.2"
    container_name: "mongo_mygopractice"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "/data/mongo_data:/data/db"
  redis:
    image: "redis:6.0"
    container_name: "redis_mygopractice"
    restart: always
    ports:
      - "6379:6379"