version: '3'
services:
  mysql:
    image: "mysql:5.7"
    container_name: "mysql_mygopractice"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Mygopractice123!"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - "./mysql_data:/var/lib/mysql"
  mongo:
    image: "mongo:4.2"
    container_name: "mongo_mygopractice"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "./mongo_data:/data/db"
  redis:
    image: "redis:6.0"
    container_name: "redis_mygopractice"
    restart: always
    ports:
      - "6379:6379"
  etcd1:
    image: "quay.io/coreos/etcd:v3.3.25"
    container_name: "etcd1_mygopractice"
    restart: always
    ports:
      - "2379:2379"
    environment:
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_NAME=etcd1"
      - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380"
      - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
      - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379"
      - "ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-mygopractice"
      - "ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      - "ETCD_INITIAL_CLUSTER_STATE=new"
  etcd2:
    image: "quay.io/coreos/etcd:v3.3.25"
    container_name: "etcd2_mygopractice"
    restart: always
    ports:
      - "22379:2379"
    environment:
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_NAME=etcd2"
      - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380"
      - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
      - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379"
      - "ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-mygopractice"
      - "ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      - "ETCD_INITIAL_CLUSTER_STATE=new"
  etcd3:
    image: "quay.io/coreos/etcd:v3.3.25"
    container_name: "etcd3_mygopractice"
    restart: always
    ports:
      - "32379:2379"
    environment:
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_NAME=etcd3"
      - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380"
      - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
      - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379"
      - "ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster-mygopractice"
      - "ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      - "ETCD_INITIAL_CLUSTER_STATE=new"
  nsqlookupd:
    image: nsqio/nsq
    container_name: "nsqlookupd_mygopractice"
    restart: always
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    container_name: "nsqd_mygopractice"
    restart: always
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=127.0.0.1 --data-path=/nsq_data
    ports:
      - "4150:4150"
      - "4151:4151"
    volumes:
      - "./nsq_data:/nsq_data"
  nsqadmin:
    image: nsqio/nsq
    container_name: "nsqadmin_mygopractice"
    restart: always
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    ports:
      - "4171:4171"